repos:
  # default built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        require_serial: true
        entry: poetry run ruff check
        types_or: [ python, pyi ]
        args: [ '--force-exclude' ]

      - id: isort
        name: isort
        language: system
        entry: poetry run isort
        require_serial: true
        types_or: [ cython, pyi, python ]
        args: [ '--filter-files', '--profile', 'black' ]

      - id: black
        name: black
        language: system
        entry: poetry run black
        require_serial: true
        types_or: [ python, pyi ]

      - id: commitizen
        name: commitizen
        language: system
        entry: poetry run cz
        args: [ 'check', '--commit-msg-file', '.git/COMMIT_EDITMSG' ]
        stages: [ commit-msg ]
        pass_filenames: false
        always_run: true
